# Generated by Django 4.2.30 on 2026-08-13 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # Tell Django 'Tenant' exists in state, but skip creating the table in Postgres
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Tenant',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(max_length=255)),
                        ('tenant_id', models.CharField(max_length=100, unique=True)),
                        ('db_schema', models.CharField(max_length=100, unique=True)),
                    ],
                    options={
                        'db_table': 'tenants',
                    },
                ),
            ],
            database_operations=[],  # Do NOT run CREATE TABLE tenants in PostgreSQL
        ),
        
        # Create the Project table in PostgreSQL
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rls_projects', to='app.tenant')),
            ],
        ),
    ]